# The PEP 484 type hints stub file for the Qt module.
#
# Generated by SIP 4.18


from PyQt5.QtCore import *
from PyQt5.QtDBus import *
from PyQt5.QtGui import *
from PyQt5.QtNetwork import *
from PyQt5.QtQml import *
from PyQt5.QtWidgets import *
from PyQt5.QtXml import *
from PyQt5.QtOpenGL import *
from PyQt5.QtPrintSupport import *
from PyQt5.QtQuick import *
from PyQt5.QtSql import *
from PyQt5.QtSvg import *
from PyQt5.QtTest import *
from PyQt5.QtX11Extras import *
from PyQt5.QtQuickWidgets import *
