# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ultiscantastic.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ultiscantastic.proto',
  package='Scanner',
  serialized_pb=_b('\n\x14ultiscantastic.proto\x12\x07Scanner\"F\n\x15PointCloudWithNormals\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08vertices\x18\x02 \x01(\x0c\x12\x0f\n\x07normals\x18\x03 \x01(\x0c\"8\n\x18PointCloudWithoutNormals\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08vertices\x18\x02 \x01(\x0c\"2\n\x0eProgressUpdate\x12\x10\n\x08objectId\x18\x01 \x01(\x05\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x05\"F\n\x04Mesh\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08vertices\x18\x02 \x01(\x0c\x12\x0f\n\x07normals\x18\x03 \x01(\x0c\x12\x0f\n\x07indices\x18\x04 \x01(\x0c\"u\n\x10StartCalibration\x12\x37\n\x04type\x18\x01 \x01(\x0e\x32).Scanner.StartCalibration.CalibrationType\"(\n\x0f\x43\x61librationType\x12\n\n\x06\x43ORNER\x10\x00\x12\t\n\x05\x42OARD\x10\x01\"W\n\tStartScan\x12)\n\x04type\x18\x01 \x01(\x0e\x32\x1b.Scanner.StartScan.ScanType\"\x1f\n\x08ScanType\x12\x08\n\x04GREY\x10\x00\x12\t\n\x05PHASE\x10\x01\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_STARTCALIBRATION_CALIBRATIONTYPE = _descriptor.EnumDescriptor(
  name='CalibrationType',
  full_name='Scanner.StartCalibration.CalibrationType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CORNER', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BOARD', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=364,
  serialized_end=404,
)
_sym_db.RegisterEnumDescriptor(_STARTCALIBRATION_CALIBRATIONTYPE)

_STARTSCAN_SCANTYPE = _descriptor.EnumDescriptor(
  name='ScanType',
  full_name='Scanner.StartScan.ScanType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GREY', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PHASE', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=462,
  serialized_end=493,
)
_sym_db.RegisterEnumDescriptor(_STARTSCAN_SCANTYPE)


_POINTCLOUDWITHNORMALS = _descriptor.Descriptor(
  name='PointCloudWithNormals',
  full_name='Scanner.PointCloudWithNormals',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Scanner.PointCloudWithNormals.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vertices', full_name='Scanner.PointCloudWithNormals.vertices', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='normals', full_name='Scanner.PointCloudWithNormals.normals', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=103,
)


_POINTCLOUDWITHOUTNORMALS = _descriptor.Descriptor(
  name='PointCloudWithoutNormals',
  full_name='Scanner.PointCloudWithoutNormals',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Scanner.PointCloudWithoutNormals.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vertices', full_name='Scanner.PointCloudWithoutNormals.vertices', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=161,
)


_PROGRESSUPDATE = _descriptor.Descriptor(
  name='ProgressUpdate',
  full_name='Scanner.ProgressUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='objectId', full_name='Scanner.ProgressUpdate.objectId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='amount', full_name='Scanner.ProgressUpdate.amount', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=163,
  serialized_end=213,
)


_MESH = _descriptor.Descriptor(
  name='Mesh',
  full_name='Scanner.Mesh',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Scanner.Mesh.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vertices', full_name='Scanner.Mesh.vertices', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='normals', full_name='Scanner.Mesh.normals', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='indices', full_name='Scanner.Mesh.indices', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=215,
  serialized_end=285,
)


_STARTCALIBRATION = _descriptor.Descriptor(
  name='StartCalibration',
  full_name='Scanner.StartCalibration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='Scanner.StartCalibration.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _STARTCALIBRATION_CALIBRATIONTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=287,
  serialized_end=404,
)


_STARTSCAN = _descriptor.Descriptor(
  name='StartScan',
  full_name='Scanner.StartScan',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='Scanner.StartScan.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _STARTSCAN_SCANTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=406,
  serialized_end=493,
)

_STARTCALIBRATION.fields_by_name['type'].enum_type = _STARTCALIBRATION_CALIBRATIONTYPE
_STARTCALIBRATION_CALIBRATIONTYPE.containing_type = _STARTCALIBRATION
_STARTSCAN.fields_by_name['type'].enum_type = _STARTSCAN_SCANTYPE
_STARTSCAN_SCANTYPE.containing_type = _STARTSCAN
DESCRIPTOR.message_types_by_name['PointCloudWithNormals'] = _POINTCLOUDWITHNORMALS
DESCRIPTOR.message_types_by_name['PointCloudWithoutNormals'] = _POINTCLOUDWITHOUTNORMALS
DESCRIPTOR.message_types_by_name['ProgressUpdate'] = _PROGRESSUPDATE
DESCRIPTOR.message_types_by_name['Mesh'] = _MESH
DESCRIPTOR.message_types_by_name['StartCalibration'] = _STARTCALIBRATION
DESCRIPTOR.message_types_by_name['StartScan'] = _STARTSCAN

PointCloudWithNormals = _reflection.GeneratedProtocolMessageType('PointCloudWithNormals', (_message.Message,), dict(
  DESCRIPTOR = _POINTCLOUDWITHNORMALS,
  __module__ = 'ultiscantastic_pb2'
  # @@protoc_insertion_point(class_scope:Scanner.PointCloudWithNormals)
  ))
_sym_db.RegisterMessage(PointCloudWithNormals)

PointCloudWithoutNormals = _reflection.GeneratedProtocolMessageType('PointCloudWithoutNormals', (_message.Message,), dict(
  DESCRIPTOR = _POINTCLOUDWITHOUTNORMALS,
  __module__ = 'ultiscantastic_pb2'
  # @@protoc_insertion_point(class_scope:Scanner.PointCloudWithoutNormals)
  ))
_sym_db.RegisterMessage(PointCloudWithoutNormals)

ProgressUpdate = _reflection.GeneratedProtocolMessageType('ProgressUpdate', (_message.Message,), dict(
  DESCRIPTOR = _PROGRESSUPDATE,
  __module__ = 'ultiscantastic_pb2'
  # @@protoc_insertion_point(class_scope:Scanner.ProgressUpdate)
  ))
_sym_db.RegisterMessage(ProgressUpdate)

Mesh = _reflection.GeneratedProtocolMessageType('Mesh', (_message.Message,), dict(
  DESCRIPTOR = _MESH,
  __module__ = 'ultiscantastic_pb2'
  # @@protoc_insertion_point(class_scope:Scanner.Mesh)
  ))
_sym_db.RegisterMessage(Mesh)

StartCalibration = _reflection.GeneratedProtocolMessageType('StartCalibration', (_message.Message,), dict(
  DESCRIPTOR = _STARTCALIBRATION,
  __module__ = 'ultiscantastic_pb2'
  # @@protoc_insertion_point(class_scope:Scanner.StartCalibration)
  ))
_sym_db.RegisterMessage(StartCalibration)

StartScan = _reflection.GeneratedProtocolMessageType('StartScan', (_message.Message,), dict(
  DESCRIPTOR = _STARTSCAN,
  __module__ = 'ultiscantastic_pb2'
  # @@protoc_insertion_point(class_scope:Scanner.StartScan)
  ))
_sym_db.RegisterMessage(StartScan)


# @@protoc_insertion_point(module_scope)
