pirate = {
    "build plate": "deck",
    "quit": "abandon ship",
    "back": "avast",
    "nozzle": "muzzle",
    "nozzles": "muzzles",
    "extruder": "cannon",
    "extruders": "cannons",
    "yes": "aye",
    "no": "nay",
    "loading": "haulin'",
    "you": "ye",
    "ok": "arrr",
    "machine": "ship",
    "machines": "ships",
    "printer": "ship",
    "printers": "ships",
    "view": "spyglass",
    "support": "peg legs",
    "file": "treasure",
    "file(s)": "treasure(s)",
    "files": "treasures",
    "profile": "map",
    "profiles": "maps",
    "setting": "knob",
    "settings": "knobs",
    "your": "yer",
    "the": "th'",
    "are": "be",
    "is": "be",
    "there": "thar",
    "not": "nay",
    "delete": "send to Davy Jones' locker",
    "remove": "send to Davy Jones' locker",
    "print": "scribble",
    "printing": "scribblin'",
    "load": "haul",
}
