---
name: CI/CD
on: [push, pull_request]
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    container: ultimaker/cura-build-environment
    steps:
    - name: Checkout master
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
    - name: Lint Python code for undefined names
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Build and test
      run: docker/build.sh
