name: process-pull-request

on:
  pull_request_target:
    types: [ opened, reopened, edited, review_requested, ready_for_review, assigned ]

# FIXME: Use `main` instead of `CURA-10831` once merged
jobs:
  add_label:
    uses: ultimaker/cura-workflows/.github/workflows/process-pull-request.yml@CURA-10831
    secrets: inherit